- name: Deploy Terraform script with Tower
  hosts: ec2-52-16-29-246.eu-west-1.compute.amazonaws.com
  become: yes
  remote_user: ec2-user
  gather_facts: no
  collections:  
    - community.general

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /tmp/terra-script
        state: directory
        mode: '0755'

    - name: Copy over the right inventory file
      template:
        src: terraform/main.tf.j2
        dest: /tmp/terra-script/main.tf

    - command: sudp pip3 install awscli

    - command: terraform init
      args:
        chdir: /tmp/terra-script

    - name: Basic deploy of a service
      community.general.terraform:
        project_path: /tmp/terra-script
        state: present
        binary_path: /usr/local/bin/terraform