- name: Deploy Terraform script with Tower
  hosts: localhost
  become: yes
  remote_user: ec2-user
  collections:  
    - community.general

  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /tmp/terra-script
        state: directory
        mode: '0755'

    - name: Copy over the right inventory file
      template:
        src: /terraform/main.tf.j2
        dest: /tmp/terra-script/main.tf

    - name: Basic deploy of a service
      community.general.terraform:
        project_path: /tmp/terra-script
        state: present