- name: Register a subscription and a host with Insights
  hosts: all
  collections:   # Define collections to search
    - redhat.insights

  tasks:
    - name: Register as user with password and auto-subscribe to available content.
      community.general.redhat_subscription:
        state: present
        username: "{{ redhat_portal_username }}"
        password: "{{ redhat_portal_password }}"
        auto_attach: true

    - include_role: 
        name: insights_client
      when: ansible_os_family == 'RedHat'
        
