- name: Test the insights collection
  hosts: all
  collections:   # Define collections to search
    - redhat.insights

  tasks:
    - include_role: 
        name: insights_client
      when: ansible_os_family == 'RedHat'
        
