- name: Register a subscription and a host with Insights
  hosts: all
  become: yes
  remote_user: ec2-user
  collections:   # Define collections to search
    - redhatinsights.insights

  tasks:
    - include_role: 
        name: insights_client
      when: ansible_os_family == 'RedHat'

