- name: Register a host with insights
  hosts: all
  collections:
    - redhat.insights.insights
    
  tasks:
    - include_role: 
        name: insights_client
      when: ansible_os_family == 'RedHat'